---
# Example Kubernetes Secret
apiVersion: v1
kind: Secret
metadata:
  name: basic-auth-header
  namespace: default
type: Opaque
stringData:
  token: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
